apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
data:
  DB_HOST: "taskflow-db.csb8wui0i2kc.us-east-1.rds.amazonaws.com"   
  DB_PORT: "3306"
  DB_NAME: "taskflow"