apiVersion: apps/v1
kind: Deployment

metadata:
  name: taskflow
  namespace: taskflow

spec:
  replicas: 2

  selector:
    matchLabels:
      app: taskflow

  template:
    metadata:
      labels:
        app: taskflow

    spec:
      containers:
      - name: taskflow

        image: sravani2310/taskflow:latest

        ports:
        - containerPort: 8080

        env:

        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: taskflow-config
              key: DB_HOST

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: taskflow-config
              key: DB_PORT

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: taskflow-config
              key: DB_NAME

        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_USERNAME

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15