pipeline {
    agent any

    tools {
        maven 'maven_3'
    }

    environment {
        DOCKER_IMAGE = "sravani2310/taskflow"
      

        SONAR_HOST = "http://44.195.26.187:9000"

        GIT_REPO_NAME = "taskflow-devop"
        GIT_USER_NAME = "SravaniTatini"
    }

    stages {

        stage('Checkout') {
            steps {
                echo "✅ Cloning GitHub Repo"
                git branch: 'main', url: "https://github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git"
            }
        }

    stage('Start MySQL Container') {
            steps {
                echo "Starting MySQL Docker container"
                sh """
                    docker rm -f ${MYSQL_CONTAINER} || true

                    docker run -d \
                    --name ${MYSQL_CONTAINER} \
                    -e MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} \
                    -e MYSQL_DATABASE=${MYSQL_DATABASE} \
                    -p 3306:3306 \
                    mysql:8
                """
            }
        }

        stage('Wait for MySQL') {
            steps {
                echo "Waiting for MySQL to start..."
                sh "sleep 25"
            }
        }



        stage('Building WAR') {
            steps {
                echo "✅ Building Spring Boot Application "
                dir("app/taskflow") {
                    sh "mvn clean package -DskipTests"
                    sh "ls -ltr target"
                }
            }
        }

        stage('SonarQube Scan') {
            steps {
                echo "✅ Running SonarQube scan"

                dir("app/taskflow") {
                    withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                        sh """
                            mvn sonar:sonar \
                            -Dsonar.projectKey=taskflow \
                            -Dsonar.host.url=${SONAR_HOST} \
                            -Dsonar.token=${SONAR_TOKEN}
                        """
                    }
                }
            }
        }

        stage('Building Docker Image') {
            steps {
                echo "✅ Building Docker image"
                sh """
                    docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} -f app/taskflow/Dockerfile app/taskflow
                    docker tag ${DOCKER_IMAGE}:${BUILD_NUMBER} ${DOCKER_IMAGE}:latest
                """
            }
        }

        stage('Trivy Scan -Image') {
            steps {
                echo "✅ Trivy Security scan for Docker image"
                sh """
                    trivy image --no-progress ${DOCKER_IMAGE}:${BUILD_NUMBER}
                """
            }
        }

        stage('Push Docker Image') {
            steps {
                echo "✅ Pushing image to DockerHub"
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    '''
                }

                sh """
                    docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}
                    docker push ${DOCKER_IMAGE}:latest
                """
            }
        }

    }
}