pipeline {
    agent any

    tools {
        maven 'maven_3'
    
    }

    environment {
        DOCKER_IMAGE = "sravani2310/taskflow"

        GIT_REPO_NAME = "taskflow-devop"
        GIT_USER_NAME = "SravaniTatini"

        
        SONAR_TOKEN = credentials('sonar-token')
    
    }

    stages {

        stage('Checkout') {
            steps {
                echo "✅ Cloning GitHub Repo"
                git branch: 'main', url: "https://github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git"
            }
        }


        stage('Building WAR') {
            steps {
                echo "✅ Building Spring Boot Application "
                dir("app/taskflow") {
                    sh "mvn clean package -DskipTests"
                    sh "ls -ltr target"
                }
            }
        }

        stage('SonarQube Scan') {
           steps {
               dir("app/taskflow") {
                  withSonarQubeEnv('SonarQube') {
                     withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                        sh """
                        mvn clean verify sonar:sonar \
                        -Dsonar.projectKey=taskflow \
                        -Dsonar.host.url=$SONAR_HOST \
                        -Dsonar.login=$SONAR_TOKEN
                        """
                        } 
                    }
                }
            }  
        }

        stage('Building Docker Image') {
            steps {
                echo "✅ Building Docker image"
                sh """
                    docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} -f app/taskflow/Dockerfile app/taskflow
                    docker tag ${DOCKER_IMAGE}:${BUILD_NUMBER} ${DOCKER_IMAGE}:latest
                """
            }
        }


        stage('Trivy Scan') {
            steps {
                echo "✅ Trivy Security scan for Docker image"
                sh '''
                TMPDIR=/home/jenkins/tmp trivy image \
                --scanners vuln \
                --severity CRITICAL \
                --exit-code 0 \
                --no-progress \
                ${DOCKER_IMAGE}:${BUILD_NUMBER}
             '''
             }
     }

        stage('Push Docker Image') {
            steps {
                echo "✅ Pushing image to DockerHub"
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    '''
                }

                sh """
                    docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}
                    docker push ${DOCKER_IMAGE}:latest
                """
            }
        }

    }
}