apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: taskflow

spec:

  project: default

  source:
    repoURL: https://github.com/yourrepo/taskflow-devops-platform
    path: kubernetes
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
